### ISSUE TITLE
Acronia Tv

### ISSUE THREAD

**Issue by Clipperboi** [Tempest0580/tempest0580.github.io#2]
Hi,
 I was wonder if you could help me with this message I keep getting "Could not deobfuscate the code" is there a way for me to fix this?
Thank you So Much

**Comment by Tempest0580** [comment]
Arconaitv is broken until I can find a fix or a replacement source. The owner of the site changed his code to block the use of it in kodi.

**Comment by Clipperboi** [comment]
Thank you for getting back to me. I'm new to kodi and trying to figure out how to use it. Sent via the Samsung Galaxy S9, an AT&T 5G Evolution capable smartphone
-------- Original message --------From: Tempest <notifications@github.com> Date: 4/18/20  8:46 PM  (GMT-05:00) To: "Tempest0580/tempest0580.github.io" <tempest0580.github.io@noreply.github.com> Cc: Clipperboi <dbdennison83@gmail.com>, Author <author@noreply.github.com> Subject: Re: [Tempest0580/tempest0580.github.io] Acronia Tv (#2) 
Arconaitv is broken until I can find a fix or a replacement source. The owner of the site changed his code to block the use of it in kodi.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/Tempest0580/tempest0580.github.io/issues/2#issuecomment-615995008",
"url": "https://github.com/Tempest0580/tempest0580.github.io/issues/2#issuecomment-615995008",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
